#!/bin/bash
###############################################################################
# This script is the command that is executed every run.
# Check the examples in examples/
#
# This script is run in the execution directory (execDir, --exec-dir),
# the same directory where target-evaluator is executed. Hence, you may
# need to copy extra files needed by the executable to this directory.
#
#
# PARAMETERS:
# $1 is the candidate number
# $2 is the instance id
# $3 is the seed
# $4 is the instance name
# The rest ($* after `shift 4') are parameters to the run
#
# RETURN VALUE:
# This script should print nothing.
# Exit with 0 if no error, with 1 in case of error
###############################################################################
error() {
    echo "`TZ=UTC date`: $0: error: $@"
    exit 1
}

DIR=`pwd`
HM=$HOME

EXE=../../build/EVRP_meta
FIXED_PARAMS="num_threads 1"

CONFIG_ID=$1
INSTANCE_ID=$2
SEED=$3

INSTANCE=$4
readarray -d / -t inst_split <<< $INSTANCE
INSTANCE="../../${inst_split[-4]}/${inst_split[-3]}/${inst_split[-2]}/${inst_split[-1]}"

shift 4 || error "Not enough parameters"
CONFIG_PARAMS=$*
CONFIG_FILE=./config_${CONFIG_ID}-${INSTANCE_ID}-${SEED}.json

stringarray=($CONFIG_PARAMS)
TIMEOUT=${stringarray[1]} # in seconds
TIMEOUT=$(($TIMEOUT/60)) # in minutes
TIMEOUT=$(($TIMEOUT+15)) # + reserve
TIMEOUT_HOURS=$(($TIMEOUT/60)) 
TIMEOUT_MINUTES=$(($TIMEOUT%60))

python3 ../../scripts/common/create_config.py $CONFIG_FILE $FIXED_PARAMS $CONFIG_PARAMS
sed -i 's/"/\\"/g' $CONFIG_FILE
CONFIG=`cat $CONFIG_FILE`
sed -i 's/\\//g' $CONFIG_FILE

STDOUT=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stdout
STDERR=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr

CMD="$EXE -d $INSTANCE -s $SEED -c $CONFIG_FILE"
CMD=`echo "$CMD" | tr '\n' ' '` 

# PBS just prints the jobID, so it should be good to go.
OUTPUT="Connection refused"
while [[ $OUTPUT == *"Connection refused"* || $OUTPUT == *"errno=111"* ]]
do
    OUTPUT=$(qsub <<EOF
#!/bin/bash
#PBS -q default@meta-pbs.metacentrum.cz
#PBS -l walltime=$TIMEOUT_HOURS:$TIMEOUT_MINUTES:0
#PBS -l select=1:ncpus=1:mem=4gb:scratch_local=16gb:cl_carex=False:cl_draba=False:cl_vinca=False
#PBS -N EVRP-LS-batch
#PBS -o $DIR/$STDOUT
#PBS -e $DIR/$STDERR

cd \$SCRATCHDIR

cp /storage/praha1/home/pazoudav/permutator ./ -r
cd permutator
rm -r -f build

module purge
module add cmake
cmake -S . -B"build" 
cmake --build build

cd tuning_setups/tuning_EVRP/
echo "${CONFIG}" > $CONFIG_FILE
cat $CONFIG_FILE >& 2
echo $CMD >& 2
eval "$CMD"
RET=\$?
echo "OK" >& 2
cd \$SCRATCHDIR
rm permutator -rf
trap 'clean_scratch' TERM EXIT
exit \$RET
EOF
2>&1)

    if [[ $OUTPUT == *"Connection refused"* || $OUTPUT == *"errno=111"* ]]
    then
        sleep 60
    fi
done

echo "$OUTPUT"


